name       : wxsqlite3
version    : 3.3.1
release    : 1
source     :
    - http://netix.dl.sourceforge.net/project/wxcode/Components/wxSQLite3/wxsqlite3-3.3.1.tar.gz : 9e947b5920dd6de4d4effd3c9b86c328cff444bb0fbc20255c60372bc47965ff
license    : LGPL-2.1
component  : programming
summary    : wxSQLite3 is a C++ wrapper around the public domain SQLite 3.x database
description: |
    wxSQLite3 is a C++ wrapper around the public domain SQLite 3.x database
builddeps  :
    - pkgconfig(sqlite3)
    - wxwidgets-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
