name       : wxsqlite3
version    : 3.5.5
release    : 4
source     :
    - https://github.com/utelle/wxsqlite3/archive/v3.5.5.tar.gz : 303aba23d5d3349335f6a9e56a35f0c55641b4af9c330f7074def71384e49303
license    : LGPL-2.1
component  : programming
summary    : wxSQLite3 is a C++ wrapper around the public domain SQLite 3.x database
description: |
    wxSQLite3 is a C++ wrapper around the public domain SQLite 3.x database
builddeps  :
    - pkgconfig(sqlite3)
    - wxwidgets-devel
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install

