name       : wxsqlite3
version    : 4.9.4
release    : 8
source     :
    - https://github.com/utelle/wxsqlite3/archive/refs/tags/v4.9.4.tar.gz : 020f05951bc46e59967bb48825799549cd8b79704c05358e972b86d4656c10e4
license    : LGPL-3.0-or-later WITH WxWindows-exception-3.1
component  : programming
summary    : wxSQLite3 is a C++ wrapper around the public domain SQLite 3.x database
description: |
    wxSQLite3 is a C++ wrapper around the public domain SQLite 3.x database.
builddeps  :
    - pkgconfig(sqlite3)
    - wxwidgets-devel
setup      : |
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install
